# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 01:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalRescue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterparent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Please format phone number as: (123) 456-7890', regex='(\\+\\d{1})?[\\s.-]?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s-.]?\\d{4}$')]),
        ),
    ]
