# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 02:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalRescue_app', '0003_auto_20180509_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fosterparent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Please format phone number as: (555) 123-4567', regex='^\\(?\\d{3}\\)?[\\s-]?\\d{3}[\\s-]?\\d{4}$')]),
        ),
    ]
